// Core logic behind the "Demo-Projekte generieren" action on
// /admin/demo-daten (and behind scripts/generate-demo-listings.ts, a thin
// CLI wrapper around the same function). See shared.ts for the rationale
// behind using synthetic data instead of scraping real platforms.
//
// Project name/motto/"So leben wir"/"Wen wir suchen" are all generated by
// combining independent word/sentence banks (see the *_STEMS, *_PART_A/B,
// SLOT_* constants below) rather than picked whole from one small fixed
// list — that's what makes every generated listing's text unique (see
// pickUniqueComposed in shared.ts) instead of the same handful of strings
// repeating once more than a few dozen listings exist. Each bank is a set of
// grammatically self-contained fragments (whole sentences, or whole
// compound-noun parts), so any recombination stays coherent — no
// mid-sentence word-swapping that could produce broken German grammar.

import {
  CITIES,
  DEMO_EMAIL_DOMAIN,
  attachRandomPhoto,
  chance,
  jitterCoord,
  maybe,
  pick,
  pickMultiple,
  pickUniqueComposed,
  prisma,
  randomInt,
  randomName,
  randomPhone,
  STREET_NAMES,
} from "./shared";
import { setListingLocation } from "@/lib/geo";

// --- Project name ------------------------------------------------------
// Compound nouns concatenate cleanly in German (no case/gender agreement
// needed within the compound), so stem+suffix is a grammatically bulletproof
// way to generate large numbers of plausible-sounding names; the curated
// phrases add variety in a few other proven patterns ("Zum X", "Die X", ...).

const NAME_STEMS = [
  "Kartoffel", "Wurzel", "Regenbogen", "Sonnenblumen", "Löwenzahn", "Kompost",
  "Mondschein", "Sternen", "Kuckucks", "Gänseblümchen", "Streuobst", "Zauberberg",
  "Krähen", "Waldschrat", "Wildbienen", "Rübenacker", "Distel", "Brennnessel",
  "Ginster", "Schafgarbe", "Holunder", "Kirschbaum", "Apfelbaum", "Birken",
  "Eichen", "Weiden", "Ulmen", "Farn", "Klee", "Heide", "Schilf", "Seerosen",
  "Libellen", "Glühwürmchen", "Grillen", "Igel", "Dachs", "Fuchs", "Eulen",
  "Kranich", "Storchen", "Schwalben", "Amsel", "Spatzen", "Raben", "Elstern",
  "Wiesel", "Biber", "Hasel", "Wacholder",
];

const NAME_SUFFIXES = [
  "hof", "kommune", "kollektiv", "scheune", "siedlung", "dorf", "garten",
  "werk", "runde", "republik", "nest", "farm", "weide", "acker", "haus",
  "zelt", "kreis", "bund", "wiese", "quartier", "hain", "grund", "winkel", "burg",
];

const NAME_REGION_TAGS = [
  "Nord", "Süd", "Ost", "West", "Mitte", "eG", "e.V.", "im Grünen", "am Bach", "am Waldrand",
];

const CURATED_NAME_PHRASES = [
  "Wolkenkuckucksheim", "Kartoffelkommune Nord", "Zur Bunten Kuh", "Nest der Wildgänse",
  "Sonnenblumenhof", "Die Schrägen Vögel", "Regenbogenscheune", "Villa Kunterbunt e.V.",
  "Zum Glücklichen Maulwurf", "Gänseblümchen-Kollektiv", "Haus Wurzelwerk", "Die Wolkenschieber",
  "Löwenzahn-WG", "Kompott & Konsorten", "Zur Letzten Instanz", "Wildkräuterhof Sausewind",
  "Die Nesthocker", "Kuckucksuhr-Kommune", "Streuobstwiese Nimmerland", "Zur Schnecke",
  "Hoffnungsvoll & Barfuß", "Die Bodenständigen", "Sternenzelt Ökodorf", "Waldschrat-WG",
  "Zum Wilden Hafer", "Die Wurzelkinder", "Krähennest Kollektiv", "Zauberberg-Kommune",
  "Die Federleichten", "Nachbarschaft Nimmerdorf", "Zum Guten Ton", "Sonnenklar-Siedlung",
  "Die Wolkenschaukel", "Rübenacker-Runde", "Freigeist-Farm", "Zur Achterbahn des Lebens",
  "Die Kartoffelkäfer", "Mondscheingasse-WG", "Zum Fröhlichen Frosch", "Wildbienenweide",
  "Die Sturköpfe", "Regenwurm-Republik", "Zur Guten Hoffnung", "Kompass & Kompost",
  "Die Weitblicker", "Blaue Stunde Kollektiv", "Zwergenhausen", "Die Nomaden-Nische",
  "Sonnenwendhof", "Klabautermann-Kommune",
  "Wolkenkuckucksnest", "Zur Wilden Minze", "Die Nachteulen", "Sonnentau-Kollektiv",
  "Haus Regenperle", "Die Umtriebigen", "Zum Tanzenden Distelfink", "Nesselgarten-WG",
  "Die Freigeister", "Zur Guten Erde", "Kleeblatt-Kommune", "Die Wolkenwanderer",
  "Zum Bunten Vogel", "Haferfeld-Kollektiv", "Die Sturmvögel", "Zur Alten Linde",
  "Wildrosenhof", "Die Nesselsucher", "Zum Zweiten Frühling", "Ginsterhügel-WG",
  "Die Kompostkönige", "Zur Offenen Tür", "Sonnentraum-Siedlung", "Die Wurzelfesten",
  "Zum Letzten Apfel", "Nachtigallenweg-Kollektiv", "Die Umherziehenden", "Zur Bunten Wiese",
  "Distelfeld-Kommune", "Die Sonnenanbeter", "Zum Fliegenden Teppich", "Wacholderhain-WG",
  "Die Nesthüpfer", "Zur Kleinen Freiheit", "Efeuranken-Kollektiv", "Die Wolkenschafe",
  "Zum Alten Brunnen", "Ringelblumenhof", "Die Nachbarschaftsgeister", "Zur Guten Nachbarschaft",
  "Kastanienrunde-WG", "Die Feldhamster", "Zum Wilden Wein", "Lindenblüten-Kollektiv",
  "Die Sonnenkinder",
];

function buildProjectNameCandidate(): string {
  const base = chance(0.55)
    ? `${pick(NAME_STEMS)}${pick(NAME_SUFFIXES)}`
    : pick(CURATED_NAME_PHRASES);
  return chance(0.2) ? `${base} ${pick(NAME_REGION_TAGS)}` : base;
}

// --- Motto ---------------------------------------------------------------
// Fortune-cookie-style two-part aphorisms: any opener can pair with any
// closer since both halves are written to be open-ended on their own.

const MOTTO_PART_A = [
  "Gemeinsam wurzeln", "Zusammen wachsen", "Geteiltes Chaos", "Offene Türen",
  "Volle Töpfe", "Geteilte Gärten", "Offene Ohren", "Volle Herzen",
  "Gemeinsam lachen", "Zusammen anpacken", "Geteilte Sorgen", "Offene Arme",
  "Chaos mit Ansage", "Mehr Wir", "Ein Zuhause mit vielen Türen",
  "Hier ist immer Platz", "Wir teilen den Rasenmäher", "Jeder bringt was mit",
  "Zusammen leben", "Bei uns klopft man", "Volle Küche", "Geteilte Freude",
  "Offene Fenster", "Zusammen wohnen", "Gemeinsam kochen", "Ein Garten für alle",
  "Mehr Gemeinschaft", "Wir haben keinen Plan", "Geteilte Wege", "Zusammen älter werden",
];

const MOTTO_PART_B = [
  "einzeln blühen.", "gemeinsam bleiben.", "nie ganz allein.", "immer mit Suppe.",
  "selten leise.", "meistens laut und herzlich.", "voller Wärme.", "ohne Umwege.",
  "weniger Ich.", "statt nebeneinander wohnen.", "keiner geht leer aus.",
  "Liebe ohne Ausnahme.", "aber einen Garten.", "und wenig Schlössern.",
  "nur aus Höflichkeit.", "und die schlechte Laune.", "und noch mehr Ideen.",
  "statt für sich allein.", "und nie den Überblick.", "auch mal ohne Anmeldung.",
  "und viel Improvisation.", "an jedem Wochentag.", "solange der Vorrat reicht.",
  "auch bei Regen.", "auch wenn es kracht.", "für alle, die mögen.",
  "und dabei viel gelernt.", "auch ohne große Worte.", "in guten wie in chaotischen Zeiten.",
  "mit viel Geduld.",
];

function buildMottoCandidate(): string {
  return `${pick(MOTTO_PART_A)}, ${pick(MOTTO_PART_B)}`;
}

// --- "So leben wir" --------------------------------------------------
// Three independent slots, each a set of complete standalone sentences —
// any combination of one sentence per slot reads as a coherent short
// paragraph, since sentences don't depend on each other grammatically.

const HOW_WE_LIVE_SLOT_1 = [
  "Wir kochen abwechselnd und essen so oft es geht gemeinsam.",
  "Beim Frühstück ist meistens jemand da, zum Abendessen fast immer alle.",
  "Wer keine Lust auf Gesellschaft hat, zieht sich einfach zurück, das ist bei uns völlig in Ordnung.",
  "Unser Alltag ist bunt gemischt: Manche arbeiten von zu Hause, andere pendeln.",
  "Die Küche ist bei uns der eigentliche Mittelpunkt des Hauses.",
  "Es gibt selten einen festen Speiseplan, dafür immer genug für spontanen Besuch.",
  "Morgens ist es bei uns meistens ruhig, abends wird es laut und gesellig.",
  "Wir teilen uns Vorräte, Werkzeug und ab und zu auch Sorgen.",
  "Wer mag, kocht mit, wer nicht mag, deckt wenigstens den Tisch.",
  "Unser Kühlschrank ist offiziell für alle, inoffiziell nur für Mutige.",
  "An den meisten Abenden findet sich irgendwer zum Reden in der Küche.",
  "Wir haben einen groben Essensplan, an den sich trotzdem kaum jemand hält.",
  "Frühstück ist bei uns heilig, alles danach eher Verhandlungssache.",
  "Wer kochen kann, kocht, wer nicht kochen kann, wäscht ab.",
  "Wir teilen uns eine große Vorratskammer und einen noch größeren Gewürzschrank.",
  "Unsere Wochenenden beginnen meist mit einem gemeinsamen Frühstück auf der Terrasse.",
  "Zwischen Homeoffice und Gartenarbeit trifft man sich bei uns eigentlich ständig.",
  "Wir essen gern zusammen, reden dabei aber selten übers Essen.",
  "Bei uns gibt es kein festes Abendbrot, dafür eine offene Tür in die Küche.",
  "Manche von uns sind Frühaufsteher, andere Nachteulen, es funktioniert trotzdem.",
  "Wir kochen meistens für mehr Leute, als am Tisch sitzen, und das ist Absicht.",
  "Unser Alltag richtet sich stark nach der Jahreszeit und dem, was der Garten hergibt.",
  "Wer neu einzieht, wird meistens schon beim ersten gemeinsamen Essen vertraut gemacht.",
  "Bei uns gibt es immer irgendwo eine Kanne Tee, die gerade fertig geworden ist.",
  "Wochentags ist es bei uns eher ruhig, am Wochenende kommt oft spontan Besuch dazu.",
  "Wir versuchen, möglichst viel selbst anzubauen, auch wenn nicht immer viel dabei rumkommt.",
];

const HOW_WE_LIVE_SLOT_2 = [
  "Bei uns gibt es einen festen Putzplan, den trotzdem niemand ganz einhält.",
  "Ein wöchentliches Plenum klärt bei uns alles, von der Wäscheleine bis zur Weltlage.",
  "Wir legen Wert auf offene Kommunikation und lösen Konflikte lieber im Gespräch.",
  "Es gibt bei uns keine strengen Regeln, aber viele Absprachen.",
  "Entscheidungen treffen wir im Konsens, auch wenn das manchmal dauert.",
  "Wer neu dazukommt, lernt das meiste einfach im Alltag, nicht aus einem Handbuch.",
  "Wir haben ein Ämtli-System für Aufgaben, das ungefähr zu zwei Dritteln funktioniert.",
  "Streit gibt es auch bei uns, wir versuchen aber, ihn zeitnah zu klären.",
  "Wichtige Entscheidungen besprechen wir gemeinsam, kleine trifft, wer gerade Zeit hat.",
  "Unsere Kommunikation läuft über eine Pinnwand in der Küche und viel Zuruf.",
  "Wir haben feste Zuständigkeiten, aber auch viel Verständnis, wenn mal etwas liegen bleibt.",
  "Alle zwei Wochen setzen wir uns zusammen und sprechen offen an, was gerade nervt.",
  "Bei uns darf jede:r Ideen einbringen, entschieden wird aber gemeinsam.",
  "Humor hilft uns erstaunlich oft, auch bei ernsteren Themen.",
  "Wir schreiben wichtige Absprachen auf, damit sie nicht in Vergessenheit geraten.",
  "Konflikte tragen wir lieber direkt aus als über Umwege.",
  "Bei uns hat jede:r ein Vetorecht, das zum Glück selten gebraucht wird.",
  "Wir wechseln uns mit Verantwortung ab, damit niemand allein alles trägt.",
  "Neuigkeiten und Ärger landen bei uns zuerst in der gemeinsamen Chatgruppe.",
  "Wir moderieren unsere Treffen reihum, damit nicht immer dieselben reden.",
  "Wichtige Beschlüsse hängen bei uns tatsächlich als Zettel am Kühlschrank.",
  "Wir nehmen uns Zeit für Feedback, auch wenn es manchmal unbequem ist.",
  "Bei uns gilt: reden hilft, auch wenn es erstmal unangenehm ist.",
  "Aufgaben verteilen wir nach Lust und Fähigkeit, nicht stur nach Plan.",
  "Wir haben gelernt, auch kleine Reibereien früh anzusprechen statt sie schwelen zu lassen.",
];

const HOW_WE_LIVE_SLOT_3 = [
  "Der Garten ist unser wichtigster Aufenthaltsort, außer es regnet, dann ist es die Küche.",
  "Wir haben viele gemeinsame Räume und trotzdem genug Rückzug für alle.",
  "Bei uns wächst mehr Gemüse, als wir eigentlich verarbeiten können.",
  "Unser Grundstück ist groß genug für Garten, Werkstatt und ein bisschen Wildwuchs.",
  "Wir haben ein Gästezimmer, das eigentlich nie leer steht.",
  "Im Sommer verlagert sich bei uns fast alles nach draußen.",
  "Unsere Gemeinschaftsräume sind bewusst offen gehalten, für Musik, Basteln oder einfach Rumsitzen.",
  "Wir haben ein paar Tiere, die mehr Aufmerksamkeit bekommen als so manches Möbelstück.",
  "Der Innenhof ist bei uns so etwas wie das inoffizielle Wohnzimmer des ganzen Hauses.",
  "Wir bauen und reparieren viel selbst, mit wechselndem, aber meist gutem Ergebnis.",
  "Unsere Werkstatt steht allen offen, auch wenn nicht jede:r sie gleich oft nutzt.",
  "Wir haben eine kleine Bibliothek im Flur, die stetig unkontrolliert wächst.",
  "Bei schönem Wetter isst bei uns kaum jemand drinnen.",
  "Unser Garten ist eher wild als ordentlich, und genau so mögen wir ihn.",
  "Wir teilen uns Fahrräder, Anhänger und gelegentlich auch das Auto.",
  "Unser Dachboden ist offiziell Stauraum, inoffiziell Ausweichquartier für Gäste.",
  "Wir haben eine Feuerstelle, die von März bis Oktober kaum kalt wird.",
  "Bei uns steht immer irgendwo ein halbfertiges Bauprojekt herum, meist mit gutem Grund.",
  "Unsere Gemeinschaftsküche ist größer als jede Einzelküche, die wir vorher hatten.",
  "Wir haben Hochbeete für alle, auch für die, die vorher noch nie gegärtnert haben.",
  "Der Hof ist bei uns Spielplatz, Werkstatt und Festsaal zugleich.",
  "Wir haben mehr Fahrräder als Mitglieder, das erklärt sich niemand so richtig.",
  "Unsere Räume sind bunt gemischt eingerichtet, jede Ecke erzählt eine andere Geschichte.",
  "Wir haben einen Kompost, der inzwischen fast schon Kultstatus genießt.",
  "Bei uns gibt es immer eine Ecke, in der gerade irgendetwas Neues ausprobiert wird.",
];

function buildHowWeLiveCandidate(): string {
  return [pick(HOW_WE_LIVE_SLOT_1), pick(HOW_WE_LIVE_SLOT_2), pick(HOW_WE_LIVE_SLOT_3)].join(" ");
}

// --- "Wen wir suchen" --------------------------------------------------

const WHO_WE_SEEK_SLOT_1 = [
  "Wir suchen Menschen, die gern mit anpacken und Verantwortung übernehmen.",
  "Am liebsten wären uns Mitbewohner:innen, die Gemeinschaft genauso schätzen wie ihren Rückzugsort.",
  "Uns ist wichtig, dass du Lust auf ein offenes Miteinander hast.",
  "Wer bei uns einzieht, sollte Tiere mögen, wir haben einige.",
  "Wir freuen uns über Menschen mit eigenen Ideen, die trotzdem gern gemeinsam entscheiden.",
  "Wichtig ist uns vor allem Offenheit, weniger eine bestimmte Lebensform.",
  "Wir suchen Leute, die auch mal über sich selbst lachen können.",
  "Uns ist es lieber, du bringst Neugier mit als ein perfektes Konzept.",
  "Wer gern gärtnert oder handwerkelt, ist bei uns sofort willkommen.",
  "Wir wünschen uns Mitbewohner:innen, die verlässlich sind, ohne verbissen zu sein.",
  "Am wichtigsten ist uns, dass du dich auf Gemeinschaft wirklich einlassen willst.",
  "Wir suchen jemanden, der gern Verantwortung teilt statt nur einfordert.",
];

const WHO_WE_SEEK_SLOT_2 = [
  "Vorerfahrung mit WG- oder Projektleben ist willkommen, aber kein Muss.",
  "Alter, Beruf oder Familienstand spielen bei uns keine große Rolle.",
  "Wichtiger als jede Checkliste ist uns ein gutes erstes Gespräch.",
  "Wir freuen uns über Menschen mit und ohne Kinder gleichermaßen.",
  "Ein Probewohnen vorab ist bei uns ausdrücklich möglich und erwünscht.",
  "Uns ist ein ehrliches Kennenlernen wichtiger als ein makelloser Lebenslauf.",
  "Wir sind offen für Menschen in ganz unterschiedlichen Lebensphasen.",
  "Ob introvertiert oder extrovertiert, bei uns findet beides seinen Platz.",
  "Wir legen Wert auf Zuverlässigkeit im Alltag, nicht auf Perfektion.",
  "Am Ende entscheiden wir gemeinsam, nicht nach starren Kriterien.",
  null,
  null,
];

function buildWhoWeSeekCandidate(): string {
  const second = pick(WHO_WE_SEEK_SLOT_2);
  const first = pick(WHO_WE_SEEK_SLOT_1);
  return second ? `${first} ${second}` : first;
}

async function ensureDemoOwners(count: number): Promise<string[]> {
  const ids: string[] = [];
  for (let i = 0; i < count; i++) {
    const email = `demo-owner-${i}@${DEMO_EMAIL_DOMAIN}`;
    const user = await prisma.user.upsert({
      where: { email },
      update: {},
      create: { email, name: randomName() },
    });
    ids.push(user.id);
  }
  return ids;
}

export type GenerateProgress = (current: number, total: number, message: string) => void;

/**
 * Creates `count` (clamped 1-100) synthetic, clearly-fake Wohnprojekt
 * listings with a wide randomized spread of attributes, categories, address/
 * geo data and 1-2 photos each. Every created row has `isDemo: true`, and
 * every project name/motto/"So leben wir"/"Wen wir suchen" is unique both
 * within this batch and against demo listings already in the database (see
 * pickUniqueComposed in shared.ts).
 */
export async function generateDemoListings(
  count: number,
  onProgress?: GenerateProgress,
): Promise<{ created: number }> {
  const clamped = Math.min(100, Math.max(1, Math.floor(count)));

  const ownerIds = await ensureDemoOwners(8);

  const [categories, listingGroups, existingDemoListings] = await Promise.all([
    prisma.listingCategory.findMany(),
    prisma.attributeGroup.findMany({
      where: { appliesTo: "LISTING" },
      include: { options: true },
    }),
    prisma.listing.findMany({
      where: { isDemo: true },
      select: { projectName: true, motto: true, howWeLive: true, whoWeAreLooking: true },
    }),
  ]);

  if (categories.length === 0 || listingGroups.length === 0) {
    throw new Error(
      "Keine ListingCategory/AttributeGroup-Daten gefunden. Bitte zuerst `pnpm db:seed` ausführen.",
    );
  }

  const usedNames = new Set(existingDemoListings.map((l) => l.projectName));
  const usedMottos = new Set(
    existingDemoListings.map((l) => l.motto).filter((v): v is string => Boolean(v)),
  );
  const usedHowWeLive = new Set(
    existingDemoListings.map((l) => l.howWeLive).filter((v): v is string => Boolean(v)),
  );
  const usedWhoWeSeek = new Set(
    existingDemoListings.map((l) => l.whoWeAreLooking).filter((v): v is string => Boolean(v)),
  );

  for (let i = 0; i < clamped; i++) {
    const projectName = pickUniqueComposed(buildProjectNameCandidate, usedNames);
    const motto = chance(0.85) ? pickUniqueComposed(buildMottoCandidate, usedMottos) : null;
    const howWeLive = chance(0.8) ? pickUniqueComposed(buildHowWeLiveCandidate, usedHowWeLive) : null;
    const whoWeAreLooking = chance(0.75)
      ? pickUniqueComposed(buildWhoWeSeekCandidate, usedWhoWeSeek)
      : null;

    const city = pick(CITIES);
    const hasStreet = chance(0.7);
    const isTemporary = chance(0.25);
    const groupSizeCurrent = maybe(randomInt(1, 14), 0.85);
    const publishedDaysAgo = randomInt(0, 200);

    const listing = await prisma.listing.create({
      data: {
        status: "PUBLISHED",
        isDemo: true,
        publishedAt: new Date(Date.now() - publishedDaysAgo * 24 * 60 * 60 * 1000),
        projectName,
        createdById: pick(ownerIds),
        motto,
        howWeLive,
        whoWeAreLooking,
        country: city.country,
        state: city.state,
        postalCode: city.postalCode,
        city: city.city,
        street: hasStreet ? pick(STREET_NAMES) : null,
        houseNumber: hasStreet ? String(randomInt(1, 140)) : null,
        regionDescription: hasStreet ? null : `Großraum ${city.city}`,
        latitude: jitterCoord(city.lat),
        longitude: jitterCoord(city.lng),
        contactName: maybe(randomName(), 0.5),
        contactEmail: maybe(`kontakt${randomInt(1, 999)}@${DEMO_EMAIL_DOMAIN}`, 0.5),
        contactPhone: maybe(randomPhone(), 0.4),
        isTemporary,
        moveInDate: maybe(new Date(Date.now() + randomInt(-30, 180) * 24 * 60 * 60 * 1000), 0.5),
        minStayDays: isTemporary ? randomInt(7, 60) : null,
        maxStayDays: isTemporary ? randomInt(60, 365) : null,
        searchPeriodStart: maybe(new Date(Date.now() + randomInt(0, 30) * 24 * 60 * 60 * 1000), 0.4),
        searchPeriodEnd: maybe(new Date(Date.now() + randomInt(60, 200) * 24 * 60 * 60 * 1000), 0.4),
        groupSizeCurrent,
        groupSizePlanned: maybe(randomInt(groupSizeCurrent ?? 1, 20), 0.4),
        freeSpots: maybe(randomInt(0, 5), 0.6),
        desiredAgeMin: maybe(randomInt(18, 45), 0.4),
        desiredAgeMax: maybe(randomInt(45, 99), 0.4),
        costOneTime: maybe(randomInt(0, 5000), 0.35),
        costMonthly: maybe(randomInt(150, 1200), 0.7),
        categories: {
          create: pickMultiple(categories, 3).map((c) => ({ categoryId: c.id })),
        },
      },
    });

    // One attribute option per group (respecting allowMultiple), mixed
    // wildly across all groups so every filter combination gets exercised.
    for (const group of listingGroups) {
      const selected = group.allowMultiple
        ? pickMultiple(group.options, 3)
        : chance(0.9)
          ? [pick(group.options)]
          : [];
      for (const option of selected) {
        await prisma.listingAttributeOption.create({
          data: { listingId: listing.id, optionId: option.id },
        });
      }
    }

    await setListingLocation(listing.id, listing.latitude, listing.longitude);

    // One or two photos per listing.
    const photoCount = randomInt(1, 2);
    for (let p = 0; p < photoCount; p++) {
      const stored = await attachRandomPhoto(`listings/${listing.id}`);
      if (!stored) continue;
      await prisma.media.create({
        data: {
          listingId: listing.id,
          type: "PHOTO",
          storageKey: stored.storageKey,
          thumbnailKey: stored.thumbnailKey,
          position: p,
          uploadedById: listing.createdById,
        },
      });
    }

    onProgress?.(i + 1, clamped, `${projectName} (${city.city})`);
  }

  return { created: clamped };
}
