// Core logic behind the "Demo-Projekte generieren" action on
// /admin/demo-daten (and behind scripts/generate-demo-listings.ts, a thin
// CLI wrapper around the same function). See shared.ts for the rationale
// behind using synthetic data instead of scraping real platforms.
//
// Project name/motto/"Wen wir suchen" are generated by combining
// independent word/sentence banks (see the *_STEMS, *_PART_A/B, SLOT_*
// constants below) rather than picked whole from one small fixed list —
// that's what makes every generated listing's text unique (see
// pickUniqueComposed in shared.ts) instead of the same handful of strings
// repeating once more than a few dozen listings exist. Each bank is a set of
// grammatically self-contained fragments (whole sentences, or whole
// compound-noun parts), so any recombination stays coherent — no
// mid-sentence word-swapping that could produce broken German grammar.
// "So leben wir" is the odd one out: a much longer (~200-400 word),
// deliberately absurd/over-the-top narrative composed in long-description.ts
// from per-stereotype (Handwerker, Yoga-Retreat, Sekte, ...) sentence banks,
// referencing whichever city/village the listing was placed in (see
// pickLocation() in shared.ts, which also spreads listings across small
// villages, not just big cities).

import {
  DEMO_EMAIL_DOMAIN,
  attachRandomPhoto,
  chance,
  jitterCoord,
  maybe,
  pick,
  pickLocation,
  pickMultiple,
  pickUniqueComposed,
  prisma,
  randomInt,
  randomName,
  randomPhone,
  STREET_NAMES,
} from "./shared";
import { buildLongDescriptionCandidate } from "./long-description";
import { setListingLocation } from "@/lib/geo";
import { generateListingSlug } from "@/lib/entity-slug";

// --- Project name ------------------------------------------------------
// Compound nouns concatenate cleanly in German (no case/gender agreement
// needed within the compound), so stem+suffix is a grammatically bulletproof
// way to generate large numbers of plausible-sounding names; the curated
// phrases add variety in a few other proven patterns ("Zum X", "Die X", ...).

const NAME_STEMS = [
  "Kartoffel", "Wurzel", "Regenbogen", "Sonnenblumen", "Löwenzahn", "Kompost",
  "Mondschein", "Sternen", "Kuckucks", "Gänseblümchen", "Streuobst", "Zauberberg",
  "Krähen", "Waldschrat", "Wildbienen", "Rübenacker", "Distel", "Brennnessel",
  "Ginster", "Schafgarbe", "Holunder", "Kirschbaum", "Apfelbaum", "Birken",
  "Eichen", "Weiden", "Ulmen", "Farn", "Klee", "Heide", "Schilf", "Seerosen",
  "Libellen", "Glühwürmchen", "Grillen", "Igel", "Dachs", "Fuchs", "Eulen",
  "Kranich", "Storchen", "Schwalben", "Amsel", "Spatzen", "Raben", "Elstern",
  "Wiesel", "Biber", "Hasel", "Wacholder",
];

const NAME_SUFFIXES = [
  "hof", "kommune", "kollektiv", "scheune", "siedlung", "dorf", "garten",
  "werk", "runde", "republik", "nest", "farm", "weide", "acker", "haus",
  "zelt", "kreis", "bund", "wiese", "quartier", "hain", "grund", "winkel", "burg",
];

const NAME_REGION_TAGS = [
  "Nord", "Süd", "Ost", "West", "Mitte", "eG", "e.V.", "im Grünen", "am Bach", "am Waldrand",
];

const CURATED_NAME_PHRASES = [
  "Wolkenkuckucksheim", "Kartoffelkommune Nord", "Zur Bunten Kuh", "Nest der Wildgänse",
  "Sonnenblumenhof", "Die Schrägen Vögel", "Regenbogenscheune", "Villa Kunterbunt e.V.",
  "Zum Glücklichen Maulwurf", "Gänseblümchen-Kollektiv", "Haus Wurzelwerk", "Die Wolkenschieber",
  "Löwenzahn-WG", "Kompott & Konsorten", "Zur Letzten Instanz", "Wildkräuterhof Sausewind",
  "Die Nesthocker", "Kuckucksuhr-Kommune", "Streuobstwiese Nimmerland", "Zur Schnecke",
  "Hoffnungsvoll & Barfuß", "Die Bodenständigen", "Sternenzelt Ökodorf", "Waldschrat-WG",
  "Zum Wilden Hafer", "Die Wurzelkinder", "Krähennest Kollektiv", "Zauberberg-Kommune",
  "Die Federleichten", "Nachbarschaft Nimmerdorf", "Zum Guten Ton", "Sonnenklar-Siedlung",
  "Die Wolkenschaukel", "Rübenacker-Runde", "Freigeist-Farm", "Zur Achterbahn des Lebens",
  "Die Kartoffelkäfer", "Mondscheingasse-WG", "Zum Fröhlichen Frosch", "Wildbienenweide",
  "Die Sturköpfe", "Regenwurm-Republik", "Zur Guten Hoffnung", "Kompass & Kompost",
  "Die Weitblicker", "Blaue Stunde Kollektiv", "Zwergenhausen", "Die Nomaden-Nische",
  "Sonnenwendhof", "Klabautermann-Kommune",
  "Wolkenkuckucksnest", "Zur Wilden Minze", "Die Nachteulen", "Sonnentau-Kollektiv",
  "Haus Regenperle", "Die Umtriebigen", "Zum Tanzenden Distelfink", "Nesselgarten-WG",
  "Die Freigeister", "Zur Guten Erde", "Kleeblatt-Kommune", "Die Wolkenwanderer",
  "Zum Bunten Vogel", "Haferfeld-Kollektiv", "Die Sturmvögel", "Zur Alten Linde",
  "Wildrosenhof", "Die Nesselsucher", "Zum Zweiten Frühling", "Ginsterhügel-WG",
  "Die Kompostkönige", "Zur Offenen Tür", "Sonnentraum-Siedlung", "Die Wurzelfesten",
  "Zum Letzten Apfel", "Nachtigallenweg-Kollektiv", "Die Umherziehenden", "Zur Bunten Wiese",
  "Distelfeld-Kommune", "Die Sonnenanbeter", "Zum Fliegenden Teppich", "Wacholderhain-WG",
  "Die Nesthüpfer", "Zur Kleinen Freiheit", "Efeuranken-Kollektiv", "Die Wolkenschafe",
  "Zum Alten Brunnen", "Ringelblumenhof", "Die Nachbarschaftsgeister", "Zur Guten Nachbarschaft",
  "Kastanienrunde-WG", "Die Feldhamster", "Zum Wilden Wein", "Lindenblüten-Kollektiv",
  "Die Sonnenkinder",
];

function buildProjectNameCandidate(): string {
  const base = chance(0.55)
    ? `${pick(NAME_STEMS)}${pick(NAME_SUFFIXES)}`
    : pick(CURATED_NAME_PHRASES);
  return chance(0.2) ? `${base} ${pick(NAME_REGION_TAGS)}` : base;
}

// --- Motto ---------------------------------------------------------------
// Fortune-cookie-style two-part aphorisms: any opener can pair with any
// closer since both halves are written to be open-ended on their own.

const MOTTO_PART_A = [
  "Gemeinsam wurzeln", "Zusammen wachsen", "Geteiltes Chaos", "Offene Türen",
  "Volle Töpfe", "Geteilte Gärten", "Offene Ohren", "Volle Herzen",
  "Gemeinsam lachen", "Zusammen anpacken", "Geteilte Sorgen", "Offene Arme",
  "Chaos mit Ansage", "Mehr Wir", "Ein Zuhause mit vielen Türen",
  "Hier ist immer Platz", "Wir teilen den Rasenmäher", "Jeder bringt was mit",
  "Zusammen leben", "Bei uns klopft man", "Volle Küche", "Geteilte Freude",
  "Offene Fenster", "Zusammen wohnen", "Gemeinsam kochen", "Ein Garten für alle",
  "Mehr Gemeinschaft", "Wir haben keinen Plan", "Geteilte Wege", "Zusammen älter werden",
];

const MOTTO_PART_B = [
  "einzeln blühen.", "gemeinsam bleiben.", "nie ganz allein.", "immer mit Suppe.",
  "selten leise.", "meistens laut und herzlich.", "voller Wärme.", "ohne Umwege.",
  "weniger Ich.", "statt nebeneinander wohnen.", "keiner geht leer aus.",
  "Liebe ohne Ausnahme.", "aber einen Garten.", "und wenig Schlössern.",
  "nur aus Höflichkeit.", "und die schlechte Laune.", "und noch mehr Ideen.",
  "statt für sich allein.", "und nie den Überblick.", "auch mal ohne Anmeldung.",
  "und viel Improvisation.", "an jedem Wochentag.", "solange der Vorrat reicht.",
  "auch bei Regen.", "auch wenn es kracht.", "für alle, die mögen.",
  "und dabei viel gelernt.", "auch ohne große Worte.", "in guten wie in chaotischen Zeiten.",
  "mit viel Geduld.",
];

function buildMottoCandidate(): string {
  return `${pick(MOTTO_PART_A)}, ${pick(MOTTO_PART_B)}`;
}

// --- "Wen wir suchen" --------------------------------------------------

const WHO_WE_SEEK_SLOT_1 = [
  "Wir suchen Menschen, die gern mit anpacken und Verantwortung übernehmen.",
  "Am liebsten wären uns Mitbewohner:innen, die Gemeinschaft genauso schätzen wie ihren Rückzugsort.",
  "Uns ist wichtig, dass du Lust auf ein offenes Miteinander hast.",
  "Wer bei uns einzieht, sollte Tiere mögen, wir haben einige.",
  "Wir freuen uns über Menschen mit eigenen Ideen, die trotzdem gern gemeinsam entscheiden.",
  "Wichtig ist uns vor allem Offenheit, weniger eine bestimmte Lebensform.",
  "Wir suchen Leute, die auch mal über sich selbst lachen können.",
  "Uns ist es lieber, du bringst Neugier mit als ein perfektes Konzept.",
  "Wer gern gärtnert oder handwerkelt, ist bei uns sofort willkommen.",
  "Wir wünschen uns Mitbewohner:innen, die verlässlich sind, ohne verbissen zu sein.",
  "Am wichtigsten ist uns, dass du dich auf Gemeinschaft wirklich einlassen willst.",
  "Wir suchen jemanden, der gern Verantwortung teilt statt nur einfordert.",
];

const WHO_WE_SEEK_SLOT_2 = [
  "Vorerfahrung mit WG- oder Projektleben ist willkommen, aber kein Muss.",
  "Alter, Beruf oder Familienstand spielen bei uns keine große Rolle.",
  "Wichtiger als jede Checkliste ist uns ein gutes erstes Gespräch.",
  "Wir freuen uns über Menschen mit und ohne Kinder gleichermaßen.",
  "Ein Probewohnen vorab ist bei uns ausdrücklich möglich und erwünscht.",
  "Uns ist ein ehrliches Kennenlernen wichtiger als ein makelloser Lebenslauf.",
  "Wir sind offen für Menschen in ganz unterschiedlichen Lebensphasen.",
  "Ob introvertiert oder extrovertiert, bei uns findet beides seinen Platz.",
  "Wir legen Wert auf Zuverlässigkeit im Alltag, nicht auf Perfektion.",
  "Am Ende entscheiden wir gemeinsam, nicht nach starren Kriterien.",
  null,
  null,
];

// HTML (matching what RichTextField's reduced editor can produce, see
// sanitizeRichText()'s tag allowlist) — a two-item bullet list when both
// slots roll a sentence, otherwise a single paragraph, since this feeds the
// same `whoWeAreLooking` field a real submission would.
function buildWhoWeSeekCandidate(): string {
  const second = pick(WHO_WE_SEEK_SLOT_2);
  const first = pick(WHO_WE_SEEK_SLOT_1);
  return second ? `<ul><li>${first}</li><li>${second}</li></ul>` : `<p>${first}</p>`;
}

async function ensureDemoOwners(count: number): Promise<string[]> {
  const ids: string[] = [];
  for (let i = 0; i < count; i++) {
    const email = `demo-owner-${i}@${DEMO_EMAIL_DOMAIN}`;
    const user = await prisma.user.upsert({
      where: { email },
      update: {},
      create: { email, name: randomName() },
    });
    ids.push(user.id);
  }
  return ids;
}

export type GenerateProgress = (current: number, total: number, message: string) => void;

/**
 * Creates `count` (clamped 1-100) synthetic, clearly-fake Wohnprojekt
 * listings with a wide randomized spread of attributes, categories, address/
 * geo data and 1-2 photos each. Every created row has `isDemo: true`, and
 * every project name/motto/"So leben wir"/"Wen wir suchen" is unique both
 * within this batch and against demo listings already in the database (see
 * pickUniqueComposed in shared.ts).
 */
export async function generateDemoListings(
  count: number,
  onProgress?: GenerateProgress,
): Promise<{ created: number }> {
  const clamped = Math.min(100, Math.max(1, Math.floor(count)));

  const ownerIds = await ensureDemoOwners(8);

  const [categories, listingGroups, existingDemoListings] = await Promise.all([
    prisma.listingCategory.findMany(),
    prisma.attributeGroup.findMany({
      where: { appliesTo: "LISTING" },
      include: { options: true },
    }),
    prisma.listing.findMany({
      where: { isDemo: true },
      select: { projectName: true, motto: true, howWeLive: true, whoWeAreLooking: true },
    }),
  ]);

  if (categories.length === 0 || listingGroups.length === 0) {
    throw new Error(
      "Keine ListingCategory/AttributeGroup-Daten gefunden. Bitte zuerst `pnpm db:seed` ausführen.",
    );
  }

  const usedNames = new Set(existingDemoListings.map((l) => l.projectName));
  const usedMottos = new Set(
    existingDemoListings.map((l) => l.motto).filter((v): v is string => Boolean(v)),
  );
  const usedHowWeLive = new Set(
    existingDemoListings.map((l) => l.howWeLive).filter((v): v is string => Boolean(v)),
  );
  const usedWhoWeSeek = new Set(
    existingDemoListings.map((l) => l.whoWeAreLooking).filter((v): v is string => Boolean(v)),
  );

  for (let i = 0; i < clamped; i++) {
    const { location: city, isVillage } = pickLocation();
    const projectName = pickUniqueComposed(buildProjectNameCandidate, usedNames);
    const motto = chance(0.85) ? pickUniqueComposed(buildMottoCandidate, usedMottos) : null;
    const howWeLive = chance(0.8)
      ? pickUniqueComposed(() => buildLongDescriptionCandidate(city.city, isVillage), usedHowWeLive)
      : null;
    const whoWeAreLooking = chance(0.75)
      ? pickUniqueComposed(buildWhoWeSeekCandidate, usedWhoWeSeek)
      : null;

    const hasStreet = chance(0.7);
    const isTemporary = chance(0.25);
    const groupSizeCurrent = maybe(randomInt(1, 14), 0.85);
    const publishedDaysAgo = randomInt(0, 200);

    // Realistic search periods: mostly a start date plus a week- or
    // month-length window, occasionally just a start date with no end
    // (an open-ended "looking from this date onward"), sometimes no period
    // at all (not currently searching for a specific timeframe).
    let searchPeriodStart: Date | null = null;
    let searchPeriodEnd: Date | null = null;
    if (chance(0.7)) {
      searchPeriodStart = new Date(Date.now() + randomInt(-10, 30) * 24 * 60 * 60 * 1000);
      const periodLength = pick(["week", "week", "month", "month", "open"] as const);
      if (periodLength === "week") {
        searchPeriodEnd = new Date(searchPeriodStart.getTime() + randomInt(5, 9) * 24 * 60 * 60 * 1000);
      } else if (periodLength === "month") {
        searchPeriodEnd = new Date(searchPeriodStart.getTime() + randomInt(26, 35) * 24 * 60 * 60 * 1000);
      }
      // "open" leaves searchPeriodEnd null — a start date with no end.
    }

    const listing = await prisma.listing.create({
      data: {
        status: "PUBLISHED",
        isDemo: true,
        publishedAt: new Date(Date.now() - publishedDaysAgo * 24 * 60 * 60 * 1000),
        projectName,
        slug: await generateListingSlug(projectName),
        createdById: pick(ownerIds),
        motto,
        howWeLive,
        whoWeAreLooking,
        country: city.country,
        state: city.state,
        postalCode: city.postalCode,
        city: city.city,
        street: hasStreet ? pick(STREET_NAMES) : null,
        houseNumber: hasStreet ? String(randomInt(1, 140)) : null,
        regionDescription: hasStreet ? null : `Großraum ${city.city}`,
        latitude: jitterCoord(city.lat),
        longitude: jitterCoord(city.lng),
        contactName: maybe(randomName(), 0.5),
        contactEmail: maybe(`kontakt${randomInt(1, 999)}@${DEMO_EMAIL_DOMAIN}`, 0.5),
        contactPhone: maybe(randomPhone(), 0.4),
        isTemporary,
        moveInDate: maybe(new Date(Date.now() + randomInt(-30, 180) * 24 * 60 * 60 * 1000), 0.5),
        minStayDays: isTemporary ? randomInt(7, 60) : null,
        maxStayDays: isTemporary ? randomInt(60, 365) : null,
        searchPeriodStart,
        searchPeriodEnd,
        groupSizeCurrent,
        groupSizePlanned: maybe(randomInt(groupSizeCurrent ?? 1, 20), 0.4),
        freeSpots: maybe(randomInt(0, 5), 0.6),
        desiredAgeMin: maybe(randomInt(18, 45), 0.4),
        desiredAgeMax: maybe(randomInt(45, 99), 0.4),
        costOneTime: maybe(randomInt(0, 5000), 0.35),
        costMonthly: maybe(randomInt(150, 1200), 0.7),
        categories: {
          create: pickMultiple(categories, 3).map((c) => ({ categoryId: c.id })),
        },
      },
    });

    // One attribute option per group (respecting allowMultiple), mixed
    // wildly across all groups so every filter combination gets exercised.
    for (const group of listingGroups) {
      const selected = group.allowMultiple
        ? pickMultiple(group.options, 3)
        : chance(0.9)
          ? [pick(group.options)]
          : [];
      for (const option of selected) {
        await prisma.listingAttributeOption.create({
          data: { listingId: listing.id, optionId: option.id },
        });
      }
    }

    await setListingLocation(listing.id, listing.latitude, listing.longitude);

    // Three to six photos per listing, enough to exercise a real gallery.
    const photoCount = randomInt(3, 6);
    for (let p = 0; p < photoCount; p++) {
      const stored = await attachRandomPhoto(`listings/${listing.id}`);
      if (!stored) continue;
      await prisma.media.create({
        data: {
          listingId: listing.id,
          type: "PHOTO",
          storageKey: stored.storageKey,
          thumbnailKey: stored.thumbnailKey,
          position: p,
          uploadedById: listing.createdById,
        },
      });
    }

    onProgress?.(i + 1, clamped, `${projectName} (${city.city})`);
  }

  return { created: clamped };
}
